apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.deployment.projectName }}
spec:
    replicas: 1
    selector:
        matchLabels:
            app: {{ .Values.deployment.projectName }}
    template:
        metadata:
            labels:
                app: {{ .Values.deployment.projectName }}
        spec:
            {{- if $.Values.deployment.imagepullsec }}
            imagePullSecrets:
                      - name: {{ .Values.deployment.imagepullsec }}
            {{- end }}
#
# Add Host alias of svc into pod /etc/hosts, exec only if exist hostAliases Param.
            {{- if $.Values.hostAliases }}
            hostAliases:
            {{- range $i, $alias := $.Values.hostAliases }}
                - ip: {{ $alias.ip }}
                  hostnames: {{ $alias.hostnames }}
            {{- end }}
            {{- end }}
            containers:
                - name: {{ .Values.deployment.projectName }}
                  image: {{ .Values.deployment.imagename }}:{{ .Values.deployment.imagetag }}
                  imagePullPolicy: Always
                  resources:
                      limits:
                          memory: {{ quote .Values.deployment.memoryLimit }}
                          cpu: {{ quote .Values.deployment.cpuLimit }}
                  ports:
                      - name: port-3000
                        containerPort: {{ .Values.deployment.port }}
                  env:
#
# Looping for env Value as mention in values.yaml file 
                  {{- range .Values.env }}
                    - name: {{ .name }}
                      value: {{ quote .value }}
                  {{- end }}
#
# Single secret with multiple value
#
                  {{- if $.Values.crd }}
                  {{- range $.Values.crd }}
                    - name: {{ .name }}
                      valueFrom:
                        secretKeyRef:
                           name: {{ $.Values.deployment.projectName }}-secret
                           key: {{ .name }}
                  {{- end }}
                  {{- end }}
#
# Multiple secrets
                  {{- if $.Values.crdMulti }}
                  {{- range $.Values.crdMulti }}
                    - name: {{ .name }}
                      valueFrom:
                        secretKeyRef:
                           name: {{ .secname }}
                           key: password
                  {{- end }}
                  {{- end }}

