apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.deployment.projectName }}
    namespace: {{ .Values.deployment.namespace }}
spec:
    replicas: 1
    selector:
        matchLabels:
            app: {{ .Values.deployment.projectName }}
    template:
        metadata:
            labels:
                app: {{ .Values.deployment.projectName }}
        spec:
            {{- if .Values.deployment.imagepullsec }}
            imagePullSecrets:
              - name: {{ .Values.deployment.imagepullsec }}
            {{- end }}
#
## PVC
            {{- if .Values.pvc.enabled }}
            volumes:
            {{- range .Values.pvc.mount }}
            - name: {{ $.Values.deployment.projectName }}-{{ .pvName }}
              persistentVolumeClaim:
                claimName: {{ $.Values.deployment.projectName }}-{{ .pvName }}
            {{- end }}
            {{- end }}
#
# Add Host alias of svc into pod /etc/hosts, exec only if exist hostAliases Param.
            {{- if $.Values.hostAliases }}
            hostAliases:
            {{- range $i, $alias := $.Values.hostAliases }}
                - ip: {{ $alias.ip }}
                  hostnames: {{ $alias.hostnames }}
            {{- end }}
            {{- end }}
            containers:
                - name: {{ .Values.deployment.projectName }}
                  image: {{ .Values.deployment.imagename }}:{{ .Values.deployment.imagetag }}
                  imagePullPolicy: Always
                  {{- if .Values.deployment.cpuLimit }}
                  resources:
                      limits:
                          memory: {{ quote .Values.deployment.memoryLimit }}
                          cpu: {{ quote .Values.deployment.cpuLimit }}
                  {{- end }}
                  ports:
                  {{- range .Values.deployment.port }}
                      - name: port-{{ . }}
                        containerPort: {{ . }}
                  {{- end }}

                  {{- if $.Values.env.enabled }}
                  env:
#
# Looping for env Value as mention in values.yaml file 
                  {{- range .Values.env.data }}
                    - name: {{ .name }}
                      value: {{ quote .value }}
                  {{- end }}
#
# Single secret with multiple value
#
                  {{- if $.Values.crd.enabled }}
                  {{- range $.Values.crd.creds }}
                    - name: {{ .name }}
                      valueFrom:
                        secretKeyRef:
                           name: {{ $.Values.deployment.projectName }}-secret
                           key: {{ .name }}
                  {{- end }}
                  {{- end }}
#
# Multiple secrets
                  {{- if .Values.crdMulti.enabled }}
                  {{- range $.Values.crdMulti.creds }}
                    - name: {{ .name }}
                      valueFrom:
                        secretKeyRef:
                           name: {{ .secretName }}
                           key: password
                  {{- end }}
                  {{- end }}
                  {{- end }}
#
## PVC
                  {{- if .Values.pvc.enabled }}
                  volumeMounts:
                  {{- range $.Values.pvc.mount }}
                    - mountPath: {{ .mountPath }}
                      name: {{ $.Values.deployment.projectName }}-{{ .pvName }}
                  {{- end }}
                  {{- end }}
