## Multiplte secret
#

{{- if $.Values.env.enabled }}
{{- if $.Values.crdMulti.enabled }}
{{- range $i, $crd := .Values.crdMulti.creds }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
  namespace: {{ $.Values.deployment.namespace }}
type: Opaque
data:
  password: {{ .key }}
---
{{- end }}
{{- end }}

###
#
# Single secret with multiple value

{{- if $.Values.crd.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.deployment.projectName }}-secret
  namespace: {{ $.Values.deployment.namespace }}
type: Opaque
stringData:
{{- range $.Values.crd.creds }}
    {{ .name }}: {{ .key }}
{{- end }}
{{- end }}
{{- end }}
