apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.projectName }}
  labels:
    app: {{ .Values.deployment.projectName }}
    addToHostAliases: "true"
    fqdn: {{ .Values.svc.fdqn }}
spec:
  type: {{.Values.svc.clustertype}}
  ports:
  - port: {{ .Values.deployment.port }}
    name: api
    protocol: TCP
  selector:
    app: {{ .Values.deployment.projectName }}
